# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  schedule:
    # runs every minute of the day
    - cron:  '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          python-version: '3.x'
      
      # install dependencies
      - name: Install dependencies for updating the timeline data
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
          pip install openpyxl
        
          

      # run the script to update the timeline data
      - name: Run script to update timeline data
        run: |
          cd _data
          python xlsxToYaml.py
