# This is a basic workflow to help you get started with Actions

name: Timeline Data Update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  schedule:
    # runs every minute of the day
    - cron:  '* * * * *'
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          python-version: '3.x'
      
      # install dependencies
      - name: Install dependencies for updating the timeline data
        run: |
          sudo apt-get install python3-setuptools
          python3 -m pip install --upgrade pip
          pip3 install PyYAML
          pip3 install openpyxl 
          
      - name: Run script to update timeline data  
        run: |
          cd _data
          rm _timeline_data.yml
          rm test_timeline.xlsx
          python3 xlsxToYaml.py
          
      - name: Push updated data back to repo
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add _data/timeline_data.yml
          git add _data/test_timeline.xlsx
          git commit -m "Updated timeline_data.yml"
          git push
